name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    env:
      CARGO_TERM_COLOR: always

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: rustup toolchain install nightly 
    - run: rustup default nightly

    - name: Cache Rust packages
      uses: actions/cache@v3
      env:
        cache-name: cache-rust-cargo
      with:
        key: ${{ runner.os }}-cache-rust-cargo-${{ hashFiles('**/Cargo.toml') }}
        path: ~/.cargo
        restore-keys: |
          ${{ runner.os }}-cache-rust-cargo-

    - name: Cache dependencies
      uses: actions/cache@v3
      env:
        cache-name: cache-rust-deps
      with:
        path: target
        key: ${{ runner.os }}-cache-rust-deps-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cache-rust-deps-

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
